//! The clap surface — **built from [`crate::table`]**, never written alongside it.
//!
//! Every subcommand here is generated by iterating [`crate::table::TABLE`], so there is exactly one
//! place a command can be declared. That is what makes `tests/ability_mapping.rs` meaningful: it
//! walks the *built* clap tree and resolves each leaf back through the table, in both directions
//! and with counts, so a command cannot exist without an ability and an ability row cannot exist
//! without a reachable command.

use std::path::PathBuf;

use clap::{Arg, ArgAction, Command};

use crate::certs::CertRequest;
use crate::run::Invocation;
use crate::table::{groups, Cmd, TABLE};

/// The banner every `--help` starts with. It is the first thing a user reads, and it is the
/// truth: this CLI performs no operations yet.
pub const STATUS_BANNER: &str = "\
STATUS — READ THIS FIRST. `pier` has NO TRANSPORT. Not one subcommand performs a real operation
against a coordinator: DEPOT-1's IK-authenticated, Noise-secured channel is not built, so nothing
is ever sent. Commands tagged [SCAFFOLD: sends nothing] resolve their resource and ability, check
your token, then refuse with a non-zero exit and tell you what is missing. Commands tagged
[LOCAL-ONLY: contacts no coordinator] are real and finish, and what they do is entirely local.

What IS real: the vocabulary. Every verb below maps to a kotva_depot::Ability from the CLOSED
registry in profiles/cloud.md §5.2, and every scope to the §5.1 resource grammar — so `pier box
destroy` can only ever put `destroy` on the wire, never `terminate`. Authorisation is a §18.7.3
CapabilityToken bound to one coordinator, and it FAILS CLOSED: there is no bearer-key fallback and
no unauthenticated path.";

const CERTS_LONG: &str = "\
Add a TLS certificate for a domain, in the tier where THE BOX HOLDS THE PRIVATE KEY.

WHICH TIER YOU ARE GETTING, AND WHAT IT COSTS YOU (profiles/cloud.md §3.4):

  Tier                                  Your DNS work    Key holder    Visibility
  ------------------------------------  ---------------  ------------  --------------------------
  Operator vanity (you.gw.example)      none             operator      declared
  Own domain, operator-driven ACME      one CNAME        operator      declared
> Own domain, BOX-HELD KEY              one CNAME (+1)   THE BOX       blind-routing; structural
                                                                       IFF the CAA precondition
                                                                       genuinely holds
  Operator-hosted zone (NS delegation)  the whole zone   operator      declared

`pier certs add` implements the third row and NOTHING ELSE. It will not silently fall back to a
row where the operator holds the key, because §3.4 forbids presenting one as the other. It never
asks for an NS delegation: §3.4 makes that normative — a gateway MUST NOT require delegation of
your zone. One record is a delegation you revoke by deleting a line; a zone is a captor.

The point of the third row is that it costs you nothing extra: §3.4 notes the middle two tiers
'differ only in who holds the key, not in how much the user types'. Both are one CNAME.

THE ONE-RECORD EXTRA, AND WHEN YOU NEED IT. REACH-2a's default is ACME TLS-ALPN-01: the CA dials
your name on 443, the adapter passes that handshake through, and the box answers it. No DNS write
at all. You need the `CNAME _acme-challenge` delegation (--acme-delegation) in exactly two cases:
a wildcard (CA/Browser Forum policy bars TLS-ALPN-01 there), or --exclude-tls-alpn.

WHY --exclude-tls-alpn EXISTS. REACH-1a points out that the in-path adapter routes the very
handshake TLS-ALPN-01 uses, so it can answer that challenge itself — same CAA-permitted CA, its
own ACME account — and mint a MITM certificate a bare RFC 8659 CAA record never excludes. Pinning
CAA validationmethods to exclude tls-alpn-01 closes that, at the cost of one more CNAME.

WHEN THIS IS `structural` AND WHEN IT IS ONLY `declared`. Pass
--caa-enforcement-established only if you have established that your CA actually enforces RFC 8657
`accounturi`. RFC 8657 §5.2 is explicit that domains MUST NOT assume it is effective without
explicit indication from the CA. Absent that, REACH-1a requires the honest label `declared`. Note
the asymmetry either way: this precondition is checkable by YOU, the zone owner — never by a
connecting client.

THIS COMMAND ISSUES NOTHING TODAY. It prints the plan and the exact records, then exits non-zero
with a list of the five things that are not built. See the output for that list.";

fn instance_arg() -> Arg {
    Arg::new("id")
        .help(
            "Instance id (opaque, operator-assigned). Omit to scope the request to every \
               instance of this elemental (depot:<service>/*).",
        )
        .required(false)
}

fn leaf(cmd: &'static Cmd) -> Command {
    let name = *cmd.path.last().expect("non-empty path");
    let mut c = Command::new(name).about(cmd.help_line());
    match cmd.key().as_str() {
        "certs add" => {
            c = c
                .long_about(CERTS_LONG)
                .arg(Arg::new("domain").required(true).help(
                    "The name to certify. A leading `*.` requests a wildcard, which forces DNS-01.",
                ))
                .arg(
                    Arg::new("ingress")
                        .long("ingress")
                        .required(true)
                        .value_name("HOST")
                        .help("The adapter's ingress host your name should CNAME to (REACH-1)."),
                )
                .arg(Arg::new("acme-delegation").long("acme-delegation").value_name("ZONE").help(
                    "A zone THE BOX controls, for the one-record `CNAME _acme-challenge` \
                     delegation (REACH-2a). Required for a wildcard or --exclude-tls-alpn.",
                ))
                .arg(
                    Arg::new("ca")
                        .long("ca")
                        .value_name("DOMAIN")
                        .default_value("letsencrypt.org")
                        .help("The CA your CAA record permits."),
                )
                .arg(Arg::new("acme-account").long("acme-account").value_name("URI").help(
                    "The BOX's ACME account URI, for the RFC 8657 `accounturi` CAA binding.",
                ))
                .arg(
                    Arg::new("exclude-tls-alpn")
                        .long("exclude-tls-alpn")
                        .action(ArgAction::SetTrue)
                        .help(
                            "Pin CAA validationmethods to exclude tls-alpn-01 (REACH-1a's SHOULD). \
                             Forces DNS-01, so it needs --acme-delegation.",
                        ),
                )
                .arg(
                    Arg::new("caa-enforcement-established")
                        .long("caa-enforcement-established")
                        .action(ArgAction::SetTrue)
                        .help(
                            "Assert you have established that your CA enforces RFC 8657 accounturi. \
                             Without it the plan is labelled `declared`, not `structural`.",
                        ),
                )
                .arg(
                    Arg::new("box-id")
                        .long("box-id")
                        .value_name("ID")
                        .help("The box that will serve the name (scopes the `reconfigure`)."),
                );
        }
        "logs" => {
            c = c
                .arg(
                    Arg::new("service")
                        .long("service")
                        .value_name("ELEMENTAL")
                        .value_parser(["box", "volume", "bucket", "edge-fn"])
                        .default_value("box")
                        .help("Which elemental to observe."),
                )
                .arg(
                    Arg::new("id")
                        .long("id")
                        .value_name("ID")
                        .help("Instance id."),
                )
                .arg(
                    Arg::new("follow")
                        .long("follow")
                        .short('f')
                        .action(ArgAction::SetTrue)
                        .help("Stream rather than snapshot."),
                );
        }
        "status" => {}
        "auth whoami" => {}
        "auth token" => {
            c = c
                .arg(
                    Arg::new("resource")
                        .long("resource")
                        .value_name("REF")
                        .help(
                        "The §5.1 scope to mint for, e.g. depot:box/7f3a91c2 or depot:bucket/*.",
                    ),
                )
                .arg(
                    Arg::new("ability")
                        .long("ability")
                        .value_name("VERB")
                        .help("A §5.2 ability. Anything outside the closed registry is refused."),
                );
        }
        _ => {
            c = c.arg(instance_arg());
        }
    }
    c
}

/// Build the whole `pier` command tree from the table.
pub fn build() -> Command {
    let mut root = Command::new("pier")
        .about("A CLI over the KOTVA DEPOT control plane (profiles/cloud.md §5).")
        .long_about(format!(
            "A CLI over the KOTVA DEPOT control plane (profiles/cloud.md §5).\n\n{STATUS_BANNER}"
        ))
        .subcommand_required(true)
        .arg_required_else_help(true)
        .arg(
            Arg::new("token")
                .long("token")
                .global(true)
                .value_name("FILE")
                .help(
                    "A det-CBOR §18.7.3 CapabilityToken. Or set PIER_TOKEN. No default path: a \
                       credential picked up from somewhere you did not name is one you did not \
                       know you were presenting.",
                ),
        )
        .arg(
            Arg::new("coordinator")
                .long("coordinator")
                .global(true)
                .value_name("HEX_IK")
                .help(
                    "The target coordinator's Ed25519 IK, hex. Or set PIER_COORDINATOR. \
                       Required for any DEPOT call: §5.1 binds every capability to one \
                       coordinator, and that binding cannot be checked against a target you \
                       never named.",
                ),
        );

    for g in groups() {
        // A group whose only row IS the group name (`logs`, `status`) is a leaf, not a parent.
        let single: Option<&'static Cmd> =
            TABLE.iter().find(|c| c.path.len() == 1 && c.path[0] == g);
        if let Some(cmd) = single {
            root = root.subcommand(leaf(cmd));
            continue;
        }
        let mut parent = Command::new(g)
            .about(group_about(g))
            .subcommand_required(true)
            .arg_required_else_help(true);
        for cmd in TABLE.iter().filter(|c| c.path.len() == 2 && c.path[0] == g) {
            parent = parent.subcommand(leaf(cmd));
        }
        root = root.subcommand(parent);
    }
    root
}

fn group_about(g: &str) -> &'static str {
    match g {
        "box" => "The compute elemental (§3): machines, their lifecycle, and the console cliff.",
        "volume" => "The block-storage elemental (§3): attach, resize, snapshot.",
        "bucket" => "The object-storage elemental (§3), including the §3.7 public-serving mode.",
        "fn" => "The edge-fn elemental (§3): deploy, invoke, roll back.",
        "certs" => "TLS certificates, in the tier where the BOX holds the key (REACH-2a, §3.4).",
        "auth" => "Capability tokens (§18.7.3). Not API keys — there is no bearer path.",
        _ => "",
    }
}

/// Resolve a parsed `ArgMatches` down to the leaf that was selected: its table key and its own
/// matches.
pub fn selected(m: &clap::ArgMatches) -> Option<(String, &clap::ArgMatches)> {
    let (head, sub) = m.subcommand()?;
    match sub.subcommand() {
        Some((tail, leaf_m)) => Some((format!("{head} {tail}"), leaf_m)),
        None => Some((head.to_string(), sub)),
    }
}

/// Read an optional string argument **without assuming it was defined on this subcommand**.
///
/// `ArgMatches::get_one` *panics* on an id the matched subcommand never declared — and since the
/// arguments here are per-command (`--service` only exists on `logs`, `--ingress` only on `certs
/// add`), a marshaller that reaches for every id blows up on every command that lacks one. That is
/// exactly what happened: the marshalling lived in `main.rs`, no test could reach it, and the
/// binary panicked on literally every invocation while 39 tests were green. `try_get_one` returns
/// `Err` instead of panicking, which is the only reason this is a lookup and not a landmine.
fn opt(m: &clap::ArgMatches, id: &str) -> Option<String> {
    m.try_get_one::<String>(id).ok().flatten().cloned()
}

/// Same, for flags.
fn flag(m: &clap::ArgMatches, id: &str) -> bool {
    matches!(m.try_get_one::<bool>(id), Ok(Some(true)))
}

/// Marshal parsed matches into the [`Invocation`] the dispatcher runs.
///
/// In the library, not the binary, so `tests/end_to_end.rs` can drive every command through it.
pub fn invocation(matches: &clap::ArgMatches) -> Option<Invocation> {
    let (key, leaf) = selected(matches)?;

    let cert = if key == "certs add" {
        Some(CertRequest {
            domain: opt(leaf, "domain").unwrap_or_default(),
            ingress: opt(leaf, "ingress").unwrap_or_default(),
            acme_delegation: opt(leaf, "acme-delegation"),
            ca: opt(leaf, "ca").unwrap_or_else(|| "letsencrypt.org".to_string()),
            acme_account: opt(leaf, "acme-account"),
            exclude_tls_alpn: flag(leaf, "exclude-tls-alpn"),
            caa_enforcement_established: flag(leaf, "caa-enforcement-established"),
        })
    } else {
        None
    };

    Some(Invocation {
        id: if key == "certs add" {
            opt(leaf, "box-id")
        } else {
            opt(leaf, "id")
        },
        service: opt(leaf, "service"),
        token: opt(matches, "token")
            .or_else(|| opt(leaf, "token"))
            .map(PathBuf::from),
        coordinator: opt(matches, "coordinator").or_else(|| opt(leaf, "coordinator")),
        cert,
        key,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tree_builds_and_every_leaf_parses() {
        let mut cmd = build();
        cmd.build();
        // A representative parse per shape.
        let m = build()
            .try_get_matches_from(["pier", "box", "destroy", "7f3a"])
            .unwrap();
        let (key, leaf_m) = selected(&m).unwrap();
        assert_eq!(key, "box destroy");
        assert_eq!(
            leaf_m.get_one::<String>("id").map(String::as_str),
            Some("7f3a")
        );

        let m = build().try_get_matches_from(["pier", "status"]).unwrap();
        assert_eq!(selected(&m).unwrap().0, "status");
    }

    #[test]
    fn the_status_banner_reaches_the_rendered_help() {
        let help = build().render_long_help().to_string();
        assert!(help.contains("NO TRANSPORT"), "{help}");
        assert!(help.contains("FAILS CLOSED"), "{help}");
    }

    #[test]
    fn certs_help_names_the_tier_and_the_key_holder() {
        let mut root = build();
        let certs = root
            .find_subcommand_mut("certs")
            .and_then(|c| c.find_subcommand_mut("add"))
            .expect("certs add");
        let help = certs.render_long_help().to_string();
        assert!(help.contains("BOX-HELD KEY"), "{help}");
        assert!(help.contains("NS delegation"), "{help}");
        assert!(help.contains("ISSUES NOTHING TODAY"), "{help}");
    }

    #[test]
    fn a_bare_group_is_not_runnable() {
        // `pier box` must not do something surprising; it must ask which verb.
        assert!(build().try_get_matches_from(["pier", "box"]).is_err());
        assert!(build().try_get_matches_from(["pier"]).is_err());
    }
}
